name: animated_native_splash
description: A package which automates the task of creating an animated splash
  screen in a flutter.
version: 1.3.0
homepage: https://github.com/Rexfordasamoah51/flutter_animated_splash_screen
maintainer: Rexford Asamoah

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  image: ^4.0.15
  meta: ^1.9.0
  path: ^1.8.2
  xml: ^6.2.2
  yaml: ^3.1.1
  universal_io: ^2.2.0
  

dev_dependencies: 
  flutter_lints: ^2.0.1
